### ISSUE TITLE
Provide component library to allow other components to configure alert rules to match the requirements of this component

### ISSUE THREAD

**Issue by simu** [appuio/component-openshift4-monitoring#36]
## Context

Right now, if another component wants to provide alert rules that work with the framework established by this component, that component needs to ensure that the alerts have the correct labels etc. (see e.g. https://github.com/projectsyn/component-rook-ceph/pull/3)

While components can reimplement the necessary alert labels and so forth, this leads to a lot of duplicated code. Instead this component should provide a component library which has helper functions that will ensure that alerts are correctly configured within the framework established by this component.

## Alternatives

As mentioned above, other components can try to keep up with reimplementing the requirements of the framework established by this component.

**Comment by corvus-ch** [comment]
Adding alert rules to `openshift-monitoring` namespace is officially not supported. So we should not make it easy to do so. On the contrary, we should provide alternatives.

The plan is to make use of user workload monitoring. If enabled on a cluster, components like [projectsyn/component-rook-ceph](https://github.com/projectsyn/component-rook-ceph) can create alert rules in their own namespace. If we provide some sort of library, it should target user workload monitoring.

**Comment by simu** [comment]
We don't create any additional rules in the `openshift-monitoring` namespace right now, and the intent of this issue isn't to add support for doing so, but to allow components to reuse the patching logic for alerts they're creating in their own namespaces without having to copy-paste the whole patching logic.

**Comment by simu** [comment]
Implemented in #136
