### ISSUE TITLE
Clarify docs regarding opsgenie credentials

### ISSUE THREAD

**Issue by mhutter** [appuio/component-openshift4-monitoring#40]
There can onyl be one Heartbeat integration per team, clarify documentation accordingly

**Comment by mhutter** [comment]
Will do a follow-up to #39 later this week

**Comment by simu** [comment]
This appears to be documented relatively clearly in https://hub.syn.tools/openshift4-monitoring/how-tos/opsgenie.html. @mhutter any objections to closing this issue?
