### ISSUE TITLE
Various SYN_PrometheusOperator* alertrules are missing

### ISSUE THREAD

**Issue by TheBigLee** [appuio/component-openshift4-monitoring#51]
Various PrometheusOperator* alert rules are missing the SYN_* equivalent. This leads to missed alerts. eg:

## Steps to Reproduce the Problem
There are 
On a synfected openshift4 cluster:

  1. Generate an `alertManagerConfig` with errors (eg syntax error)
  1. Compile the catalog
  1. Wait for the change to be applied
  1. The prometheusOperator will not load the new config due to errors in the config
  1. The AlertRule `PrometheusOperatorSyncFailed` will fire, but never escalated to eg. `OpsGenie`.

## Actual Behavior
Various alert rules regarding the `PrometheusOperator`are not seen in eg. `OpsGenie`

## Expected Behavior
All **relevant** alerts regarding the `PRometheusOperator` are forwarded to eg `OpsGenie`

**Comment by simu** [comment]
The rules may be defined somewhere in https://github.com/openshift/cluster-monitoring-operator, if that's the case include them analogously to the other rulefiles included in the component (see `class/openshift4-monitoring.yml`)
